# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "16:00"
      timezone: "Europe/Berlin"
    versioning-strategy: "increase-if-necessary"
    labels:
      - "dependencies"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "16:00"
      timezone: "Europe/Berlin"
    versioning-strategy: "increase-if-necessary"
    labels:
      - "dependencies"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "16:00"
      timezone: "Europe/Berlin"
    labels:
      - "dependencies"
  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "16:00"
      timezone: "Europe/Berlin"
    labels:
      - "dependencies"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "16:00"
      timezone: "Europe/Berlin"
    groups:
      all-actions:
        patterns: [ "*" ]
    labels:
      - "dependencies"
