services:
    dealer-registration:
        image: ghcr.io/eurofurence/dealer-registration:nightly
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        env_file: .env
        environment:
          APP_ENV: production
        command: /bin/sh -c 'php artisan optimize && php artisan octane:start --host=0.0.0.0
          --port=80'
        networks:
            - dealer-registration
        depends_on:
            redis:
                condition: service_healthy
            mariadb:
                condition: service_healthy
            minio:
                condition: service_healthy
            minio-init:
                condition: service_completed_successfully
            mailpit:
                condition: service_started
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - dealer-registration
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            start_period: 5s
            interval: 5s
            timeout: 5s
            retries: 30
    mariadb:
        image: 'mariadb:10'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'sail-mariadb:/var/lib/mysql'
            - './vendor/laravel/sail/database/mariadb/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - dealer-registration
        healthcheck:
            test:
                - CMD
                - healthcheck.sh
                - '--connect'
                - '--innodb_initialized'
            start_period: 5s
            interval: 5s
            timeout: 5s
            retries: 30
    minio:
        image: 'minio/minio:latest'
        ports:
            - '${FORWARD_MINIO_PORT:-9000}:9000'
            - '${FORWARD_MINIO_CONSOLE_PORT:-8900}:8900'
        environment:
            MINIO_ROOT_USER: '${AWS_ACCESS_KEY_ID}'
            MINIO_ROOT_PASSWORD: '${AWS_SECRET_ACCESS_KEY}'
        volumes:
            - 'sail-minio:/data/minio'
        networks:
            - dealer-registration
        command: 'minio server /data/minio --console-address ":8900"'
        healthcheck:
            test:
                - CMD
                - curl
                - '-f'
                - 'http://localhost:9000/minio/health/live'
            start_period: 5s
            interval: 5s
            timeout: 5s
            retries: 30
    minio-init:
        image: minio/mc
        depends_on:
            minio:
                condition: service_healthy
        environment:
            AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
            AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
            AWS_BUCKET: ${AWS_BUCKET}
            AWS_ENDPOINT: ${AWS_ENDPOINT}
        networks:
            - dealer-registration
        entrypoint: >
            /bin/sh -c "
            /usr/bin/mc config host add ef-minio ${AWS_ENDPOINT} ${AWS_ACCESS_KEY_ID} ${AWS_SECRET_ACCESS_KEY};
            /usr/bin/mc ready ef-minio;
            /usr/bin/mc mb -p ef-minio/${AWS_BUCKET};
            /usr/bin/mc anonymous set download ef-minio/${AWS_BUCKET};
            exit 0;
            "
    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - dealer-registration
networks:
    dealer-registration:
        driver: bridge
volumes:
    sail-redis:
        driver: local
    sail-mariadb:
        driver: local
    sail-minio:
        driver: local
