<?php

namespace Tests\Feature;

use App\Models\Application;
use App\Models\TableType;
use App\Models\User;
use App\Notifications\PhysicalChairsChangedNotification;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Config;
use Illuminate\Support\Facades\Notification;
use PHPUnit\Framework\Assert;
use Tests\TestCase;

class ChairNotificationTest extends TestCase
{
    use RefreshDatabase;

    private User $user;

    public function setUp(): void
    {
        parent::setUp();

        // to avoid registration fields not being filled
        Config::set('convention.reg_start_date', Carbon::yesterday());
        Config::set('convention.reg_end_date', Carbon::tomorrow());
        Config::set('convention.con_end_date', Carbon::tomorrow());

        $this->seed();
        $this->user = User::factory()->create();
        $this->actingAs($this->user);

        Notification::fake();
    }

    protected function tearDown(): void
    {
        $this->user->application?->deleteQuietly();
        $this->user->deleteQuietly();

        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function test_raw_application_creation_sends_no_notification_email()
    {
        Notification::fake();

        Application::factory()->create([
            'user_id' => $this->user->id,
        ]);

        Notification::assertNothingSent();

    }

    public function test_changing_chair_count_sends_notification_email()
    {
        Notification::fake();

        Application::factory()->create([
            'user_id' => $this->user->id,
        ]);

        $this->user->application->first()->update([
            'physical_chairs' => 2
        ]);

        Notification::assertSentTo([$this->user], PhysicalChairsChangedNotification::class);

    }

    private function assertChairCount($expected, $message)
    {
        $this->assertEquals($expected, $this->user->application->first()->physical_chairs, $message);
    }

    private function assertChairChangeNotification($newChairCount)
    {
        Notification::assertSentTo([$this->user], PhysicalChairsChangedNotification::class,
            function (PhysicalChairsChangedNotification $notification) use ($newChairCount) {
                $mail = $notification->toMail($this->user);
                Assert::assertStringContainsString(
                    sprintf('your dealership will receive %d physical chairs', $newChairCount),
                    strip_tags(join(' ', $mail->introLines)),
                    'Mail text does not contain expected information about the new seat count.');

                return true;
            });
    }

    public function test_changing_table_enforces_chair_count_and_sends_notification_email()
    {
        Notification::fake();

        // Creating a 3-seat table application with full chair count.
        Application::factory()->create([
            'user_id' => $this->user->id,
            'table_type_requested' => TableType::where(['seats' => 3])->first()->id,
            'table_type_assigned' => null,
            'physical_chairs' => 3,
        ]);

        Notification::assertNothingSent();
        $this->assertChairCount(3, 'Chair count is validly stored');

        info('Try adding too many chairs');
        $this->user->application->first()->update([
            'physical_chairs' => 4
        ]);

        $this->assertChairCount(3, 'Excessive chair count is enforced away');
        Notification::assertNothingSent();

        Notification::fake(); // clear since we expect an actual message now

        // Downgrade requested table, which should trigger a chair count reduction and email notification
        $this->user->application->first()->update([
            'table_type_requested' => TableType::where(['seats' => 2])->first()->id,
        ]);

        $this->assertChairCount(2, 'Smaller requested table enforces reduced chairs');
        $this->assertChairChangeNotification(2);

        Notification::fake(); // clear since we expect a different message now

        // Downgrade again by assinging an even smaller table, which should trigger a chair count reduction and email notification
        $this->user->application->first()->update([
            'table_type_assigned' => TableType::where(['seats' => 1])->first()->id,
        ]);

        dump($this->user->application->first()->physical_chairs);

        $this->assertChairCount(1, 'Assigning an even Smaller table enforces reduced chairs');
        $this->assertChairChangeNotification(1);

    }

}
