---
name: Bug Report
description: Report errors or unexpected behavior in the Eurofurence Dealers' Den Registration & Frontdesk Application.
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report an issue with the Eurofurence Dealers' Den Registration & Frontdesk Application. Your feedback helps us improve the platform.

        Please provide detailed information below to help us diagnose and fix the problem.
      
  - type: dropdown
    attributes:
      label: User Role
      description: Select your role when you encountered the issue.
      options:
        - Dealers' Den Staff / Director
        - Eurofurence Staff
        - Artist, Dealer
        - Dealer Assistant, Dealer Share
        - Anyone (Role doesn't matter)
    validations:
      required: true

  - type: dropdown
    attributes:
      label: System Type
      description: Select the type of device you were using.
      options:
        - Computer
        - Tablet
        - Smartphone
        - Other
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Operating System
      description: Select the operating system of your device.
      options:
        - iOS
        - macOS
        - iPadOS
        - Windows
        - Linux
        - Other
    validations:
      required: true

  - type: input
    attributes:
      label: OS Version
      description: Enter the version of your operating system.
      placeholder: e.g., Windows 11, macOS 12.3, Ubuntu 20.04
    validations:
      required: false

  - type: input
    attributes:
      label: Browser Details (if applicable)
      description: Enter the name and version of the browser you were using.
      placeholder: e.g., Chrome 93, Safari 15, Firefox 92
    validations:
      required: false

  - type: textarea
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. 
        2. 
        3. 
      description: Provide step-by-step instructions on how to reproduce the issue. This field is optional but highly encouraged.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Expected Behavior
      placeholder: Tell us what should happen
    validations:
      required: true

  - type: textarea
    attributes:
      label: Actual Behavior
      placeholder: Tell us what happens instead
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Feature Area
      description: Select the feature area where the issue occurred.
      options:
        - Registration / Application
        - Add Share(s)
        - Add Assistant(s)
        - Other
    validations:
      required: true

  - type: input
    attributes:
      label: If you selected "Other", please specify
      placeholder: Specify the general feature you were trying to use
    validations:
      required: false

  - type: dropdown
    attributes:
      label: Severity
      description: How severe is the issue?
      options:
        - Minor Issue
        - Major Issue
        - Critical Problem
    validations:
      required: true

  - type: textarea
    attributes:
      label: Error Messages
      placeholder: Paste any error messages here (if applicable)
    validations:
      required: false

  - type: textarea
    attributes:
      label: Workarounds Tried
      placeholder: Describe any temporary solutions or workarounds you have tried
    validations:
      required: false

  - type: dropdown
    attributes:
      label: Network Type
      description: Select the type of network connection you were using.
      options:
        - Wired Ethernet
        - Wi-Fi
        - Mobile Data (3G/4G/5G)
        - Other
    validations:
      required: false

  - type: textarea
    attributes:
      label: Anything Else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
