blank_issues_enabled: true
contact_links:
  - name: General Questions or Issues
    url: https://help.eurofurence.org/contact/dealer
    about: For any other questions or problems, please contact the Eurofurence Dealers' Den Department.
